{% set name = "daml" %}
{% set version = "0.45.0" %}
{% set sha256 = "78da8c004298c99bec8ec0e6ab4173802642d0c390abd7218831827ed1c3da05" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host:
    - python >=3.8.1, <3.12
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >=3.8.1, <3.12
    - numpy
    - scipy
    - scikit-learn

test:
  imports:
    - daml
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/aria-ml/daml/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Data-Analysis Metrics Library

extra:
  recipe-maintainers:
    - aria-ml
