{% set name = "daml" %}
{% set version = "0.54.0" %}
{% set sha256 = "411090eb25535a1f8264314c8b07f9c2e8e075dc25f8dc288f4fb749a9bcd6e9" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host:
    - python >=3.8.1, <3.12
    - pip
    - poetry-core
    - poetry-dynamic-versioning

  run:
    - python >=3.8.1, <3.12
    - hdbscan >=0.8.36
    - numpy >=1.24.2
    - pillow >=10.3.0
    - python-xxhash >=3.3
    - scipy >=1.10
    - scikit-learn >=1.2.1

test:
  imports:
    - daml
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/aria-ml/daml/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Data-Analysis Metrics Library

extra:
  recipe-maintainers:
    - aria-ml
